### ISSUE TITLE
CloudFormation validate-template error on website-service/service.yaml

### ISSUE THREAD

**Issue by dougtoppin** [awslabs/ecs-refarch-cloudformation#55] opened 2018-02-18 15:50 UTC
Before copying CF templates to S3 I typically run validate-template on them using the aws cli. I notice that this error is now appearing when I validate:

`aws cloudformation validate-template --template-body file://services/website-service/service.yaml`

`An error occurred (ValidationError) when calling the ValidateTemplate operation: Template error: if specifying one argument to Fn::GetAtt, that argument must be a non-empty string in format <LogicalId>.<Attribute>`

I think that it might be due to the following line (error does not occur if commented out):

RoleARN: !GetAtt ECSServiceAutoScalingRoleARN

Is this expected?

**Comment by dougtoppin** [comment] 2018-02-20 14:58
I just confirmed that at the CF console as well the website-service/service.yaml generates the same validation error.

2/20/2018, 9:55:20 AM - Template contains errors.: Template error: if specifying one argument to Fn::GetAtt, that argument must be a non-empty string in format <LogicalId>.<Attribute>

**Comment by alpineElfFriend** [comment] 2018-02-22 23:11
Issue seems to be caused by invalid output for "ECSServiceAutoScalingRole" in infrastructure/ecs-cluster.yaml
Was able to replicate, should be resolved by:
https://github.com/awslabs/ecs-refarch-cloudformation/pull/57

**Closed as completed** 2018-02-23 09:03 UTC
