### ISSUE TITLE
Repeatable

### ISSUE THREAD

**Issue by daneroo** [awslabs/ecs-refarch-cloudformation#2] opened 2016-10-04 23:47 UTC
I may well be doing something wrong, 
but I cannot invoke the Stack creation twice with the same name.

That is:
- I bring up the stack (Using the Launch Stack button)
- Then completely delete it.
- I can then Launch an identical stack but **not if I re-use the same Stack Name**.

I can't for the life of me find any dangling resources which may still be present.
This is the error message in the Cloudformation Events tab:

```
19:35:28 UTC-0400   ROLLBACK_IN_PROGRESS    AWS::CloudFormation::Stack  RefTest The following resource(s) failed to create: [ALB, ECS]. . Rollback requested by user.
```

Any Ideas?

**Comment by cloudoperator** [comment] 2016-10-06 02:38
I am facing the same issue! Be nice to know what the issue is.

**Comment by JustinPlute** [comment] 2016-10-06 06:40
+1

**Comment by daneroo** [comment] 2016-10-06 15:07
I have managed to work around the problem for now,
- After cloning the s3 bucket to experiment
- Provisioning with `aws cloudformation [create|update|delete]-stack`, with explicit:
  - `--role-arn` w/ Admin privileges, as well as
  -  `--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM`

But the clincher seems to be removing the `infrastructure.yml::ECSCluster` CusterName property

```
ECSCluster:
    Type: AWS::ECS::Cluster
    # Here be dragons, this is causing stack failures on update, or re-provisioning after delete.
    # Properties:
    #     ClusterName: !Ref EnvironmentName
```

This is not ideal because the Cluster Name is no longer predictable, and is harder to use from my evolving, but independant deploy scripts...

**Comment by PaulMaddox** [comment] 2016-10-06 19:35
Thank you for reporting this. You are correct that this is related to the ClusterName parameter. The ECS/CloudFormation teams are aware and working on a fix.

**Comment by kalpik** [comment] 2016-10-14 07:03
Any updates on how it's going? :)

**Comment by PaulMaddox** [comment] 2016-11-03 22:01
Thanks again for reporting this. I believe this has now been resolved by the CloudFormation team.

I have tested by:
1. Deploying the stack to us-east-2 (Ohio)
2. Deleting the whole stack
3. Deploying the stack again, with the same stack name (successfully)

If you're still having problems, please re-open this issue.

**Closed as completed by PaulMaddox** 2016-11-03 22:01 UTC

**Comment by stevenlafl** [comment] 2021-12-01 17:25
Same exact problem, newest version of this repository.
